language: python

python:
  - 3.6

services: postgresql

env:
  global:
    - DJANGO_SETTINGS_MODULE="transgov.src.searchapp.settings"
    - PYTHONPATH="/home/travis/build/TransparentGovernanceUofA/TransparentGov"
    - PIP_USE_MIRRORS=true

install:
  - pip install -r transgov/src/requirements.txt
  - pip install codecov

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'
  - python transgov/src/manage.py test transgov/src
  - coverage run transgov/src/manage.py test transgov/src

after_success:
- codecov
